### ISSUE TITLE
Uploading BED files

### ISSUE THREAD

**Issue by nadabrovitxka** [hms-dbmi/higlass#124]
Hi,
I can digest .cool and .bw files into higlass.
But am having problems with bed files.

I ran 
`clodius aggregate bedfile test.bed`
and
`docker exec higlass-container python higlass-server/manage.py \
  ingest_tileset \
  --filename /tmp/test.bed.multires \
  --filetype bedfile \
  --datatype vector \
  --name “test_bedfile”`

I do not get an error message but Higlass just shows Loading and never shows up the signal.
Couldnt really find information on how to upload bed files.
Is the datatype in my command correct?

Here is the test <a href='https://drive.google.com/drive/folders/0B0wnRGWP-yayZ2RYX0lWSXRpTFk?usp=sharing'>file</a> I am using.
Thanks

**Comment by pkerpedjiev** [comment]
So the filetype should actually be `beddb` and the datatype should be `bed-value`. I'm working on documentation for this at the moment.

When I tried importing your file on my computer, I couldn't see anything. It's probably a bug in either higlass or clodius. I'm looking at it right now and will follow up shortly.

**Comment by pkerpedjiev** [comment]
OK, should be fixed in the latest docker container (v0.2.13).

Use `--filetype beddb --datatype bedlike`. When adding the track, you should get an option for `bedlike`. This will display the intervals specified in the bed file:

![image](https://user-images.githubusercontent.com/2143629/29530832-98177c6e-8673-11e7-93d6-94a7002b39b8.png)

**Comment by nadabrovitxka** [comment]
seems good. thank you!
