### ISSUE TITLE
higlass shows unbalanced data

### ISSUE THREAD

**Issue by Phlya** [hms-dbmi/higlass#175]
The title says it all... If I simply ingest a balanced cooler the heatmap in higlass is not balanced - quite obvious buy just looking at it, and also if comparing to `cooler show`. Is there a way to switch balanced vs non-balanced view? I can't find it anywhere, at least.

**Comment by pkerpedjiev** [comment]
Normally you can select balancing using the `transforms` configuration option:

![image](https://user-images.githubusercontent.com/2143629/32613317-d5ae044c-c527-11e7-9a58-9acd5f320540.png)

If the cooler is balanced, that should be the default option though. If you don't see an option in the menu, do you think you could share the file? I can send you my email if you don't want to make it public.

**Comment by Phlya** [comment]
OK, I only have "Default" and "None" options there, and neither of them is balanced. The file is huge, would be difficult to share... I'll try to reproduce this with a small file.
![screenshot from 2017-11-09 15-30-55](https://user-images.githubusercontent.com/2895034/32613618-553c78c0-c563-11e7-907b-4b06f1f34b27.png)

**Comment by pkerpedjiev** [comment]
While you're reproducing it with a smaller file, could you paste the command that you used to make it multires here?

**Comment by Phlya** [comment]
`cooler zoomify -p 4 --balance file.cool`

**Comment by pkerpedjiev** [comment]
That looks right. Let me know when you have a smaller file and I'll take a look to see what's happening.

**Comment by Phlya** [comment]
OK, I tried to zoomify a small file but then it didn't converge at the highest resolution... So screw it, here is a link to the huge dataset I was working with. (This is ES cell data from Bonev et al 2017)
https://datasync.ed.ac.uk/index.php/s/1DsY6gG9QiDHL11
Password ILoveHi-C

A related question - what happens if the base cooler file I use is balanced, but I don't use the --balance option during zoomifying? Will it use the balanced values for aggregation?

**Comment by Phlya** [comment]
I have to say, I tried with the same small file, but starting at low resolution, and then it was ICEd in higlass! So there is something weird going on for me.

**Comment by nvictus** [comment]
Aggregation is always at the level of raw counts. Balancing is done on each zoom level after aggregation is done. If the base zoom level was already balanced, then the existing weights are used instead.

I suspect what's happening is that is that if balancing weights are missing from any zoom level, then HiGlass won't provide it as a transform option. The plan was to change this behavior in HiGlass, but I don't think it has been rolled out yet.

More importantly, the fact that the zoomify process aborts as soon as balancing fails is not good; it's been on my todo list to fix.  We're also considering different policies for what to do on failed convergence, e.g. store NaNs, store the final result, etc. instead of not storing anything. 

An easy workaround for now is to separately balance any zoom levels that failed to converge with a higher tolerance or other parameter tweaks, e.g. `cooler balance -p 4 --tol 0.001 mycooler.cool::12`. You can check if a zoom level is balanced with `cooler balance --check <file>::<zoom>`.

**Comment by Phlya** [comment]
Thank you Nezar! That was my suspicion too... But the file in question should have all the levels balanced since it was aggregated with the `--balance` option on, and I can do `cooler show -b` on all levels (well, I haven't tried all, but both the first and the last, and a couple in the middle...). I can check this more thoroughly tomorrow to be sure.

Good idea about balancing individual levels that didn't converge, thanks!

About aggregating balanced data - wouldn't it make sense to aggregate the weights too? Then they either can be used directly (but NaNs might be a bit difficult to work around), or re-balancing higher levels will be much quicker, since weights are already close to optimal?

**Comment by Phlya** [comment]
So, I have no idea what went wrong before, I re-ingested the file and it now shows ICEd data! However another file, the NPC data from the same paper, is not working after repeating the ingestion... But again, definitely all levels are balanced! Something weird is going on here...

**Comment by pkerpedjiev** [comment]
Assuming this has been addressed. Please reopen if that isn't the case.
