### ISSUE TITLE
Displaying TAD Annotations in HiGlass

### ISSUE THREAD

**Issue by sameedms** [hms-dbmi/higlass#202]
Hi, 

First of all, thanks for the work ya'll do - it's brilliant!

In the examples page, you show [TAD annotation](http://higlass.io/app/?config=IPCHmdOQR4CDY2sqj5VJHQ) on Hi-C samples. I'm looking to recreate this view. What I have is a bed file containing the TAD boundaries. In the "Add Track" menu accessed through clicking "+" on a view, the data type is given as "horizontal-2d-rectangle-domains." The closest data type I've seen on the higlass docs is the "2d-rectangle-domains" that can be created using clodius. 

My bed file looks as follows:
```
chr21   17615000        17625000        B01762  0.016026573178  .
chr21   17975000        17985000        B01798  -0.077002446522 .
chr21   25065000        25075000        B02507  0.048794939035  .
chr21   25565000        25575000        B02557  -0.061547410392 .
chr21   25765000        25775000        B02577  0.051375443095  .
chr21   26175000        26185000        B02618  0.077178390073  .
```

```clodius aggregate bedpe``` seems like the command most suitable for translating this bed file to boundaries, so this is the command I used:

> clodius aggregate bedpe --assembly hg38 --chr1-col 1 --from1-col 1 --to1-col 2 --chr2-col 3 --from2-col 5 --to2-col 6 --output-file tad_domains.txt.multires T1_hic_10kb_matrix_fdr_0.01_boundaries.bed

I uploaded the track to my higlass instance. However, when I actually applied the track and zoomed in, no boxes appear.

The HiGlass TAD visualization example was brilliant - I'd love to be able to recreate it.

Thanks,
Sameed

**Comment by pkerpedjiev** [comment]
Hi Sameed,

So the `clodius aggregate bedpe` command is indeed what you want to use. Because it can be used for regions that aren't along the diagonal, it needs two sets of (chr, start, end) triplets. Those are indicated by the `--chr[1,2]-col`, `--from[1,2]-col`,  and `--to[1,2]-col2` parameters. The command you used passes in columns (1,2,3) and (4,5,6) for these values. In your file, however, those values are all in the first three columns. So what you need to do is to pass the same values for the second triplet:

` --chr1-col 1 --from1-col 2 --to1-col 3 --chr2-col 1 --from2-col 2 --to2-col 3`

My I ask which documentation page you looked at?

If the above solution doesn't work, could you send a screenshot of your browser's development console?

**Comment by sameedms** [comment]
Hi,

Thanks a bunch - that's exactly what I needed to change. I used [this documentation on github](https://github.com/hms-dbmi/higlass/wiki#bedpe-like-files).

Once again, thanks for the great work!

Regards,
Sameed

**Comment by LeilyR** [comment]
Hi, 

I am trying to use `clodius aggregate bedpe` on a similar type of bed files. The command I use is:
`clodius aggregate bedpe -a dm6 --chr1-col 1 --from1-col 2 --to1-col 3 --chr2-col 1 --from2-col 2 --to2-col 3 -o boundaries.txt.multires boundaries.bed`
and the entries of the bed file I use as input is like this:
`chr2L	93000	95000	B00047	0.023357889801	.`
I receive this error: 
`File "/data/processing3/leily/miniconda3/lib/python3.7/site-packages/clodius/cli/aggregate.py", line 261, in _bedpe
    entries = [line_to_dict(first_line)]
  File "/data/processing3/leily/miniconda3/lib/python3.7/site-packages/clodius/cli/aggregate.py", line 216, in line_to_dict
    d['uid'] = slugid.nice().decode('utf-8')
AttributeError: 'str' object has no attribute 'decode'`

Is this because my chromosome names are a combination of letter and numbers?

**Comment by LeilyR** [comment]
update: I have actually fixed that by just deleting the `decode('utf-8)` from the code

**Comment by pkerpedjiev** [comment]
Nice!

Do you know what version of clodius you are using? I thought we fixed that a while ago.

**Comment by LeilyR** [comment]
Actually I have just noticed that it is a very old one. It seems i have installed it in August 2019 and there is no version in its init file. I will update it.
