### ISSUE TITLE
URL mapping to localhost

### ISSUE THREAD

**Issue by aakashsur** [hms-dbmi/higlass#219]
_Commit_: latest

#### Steps to reproduce
1. create superuser for django admin page

#### Observed behavior
- http://[remote IP] works as expected
- http://[remote IP]/app redirects to  http://127.0.0.1/app/
- http://[remote IP]/app/ works as expected
- http://[remote IP]/admin redirects to http://127.0.0.1/admin/
- http://[remote IP]/admin/ works as expected

#### Expected behavior
- My understanding was that django resolves with or without a slash into the same url. (as long as the regex works out like that) I have a cloud instance running HiGlass, so the HiGlass docker container is broadcasting into the localhost, so in addition to the Nginx server running inside the container, there is an Nginx server running on the host machine. Not sure if configuration of that would cause issues, but my guess was that it had to do with the regex of the urls.py file. However with and without the final slash seems to work on higlass.io, so it could be a problem on my end.

**Comment by pkerpedjiev** [comment]
Thanks for reporting this. I've noticed issues with the trailing slash and I suspect it has to do with the nginx instance running on the Docker container.

Since there's an easy workaround I'm going to leave this issue open and swing back around to it later. If it's causing you lots of trouble, please post again and I'll try to find some time to look at it sooner.

**Comment by aakashsur** [comment]
Gotcha, take your time, it was just a random thing I noticed.

**Comment by flekschas** [comment]
Closed as the observed behavior is expected (same on higlass.io)
