### ISSUE TITLE
Auto-scaling on bigwig/hitile 

### ISSUE THREAD

**Issue by aakashsur** [hms-dbmi/higlass#223]
While I was adding some bigwig files as hitile tracks, I noticed that the scale of the line graph seems to change not quite as I would expect: (wow my gif looks super slow, maybe its too big?)

![hitile](https://user-images.githubusercontent.com/7614271/36514501-8941f308-1729-11e8-9793-55e1a0b49a0f.gif)

I figured once larger data points are out of view it would rescale. Do you suggest any remedies, like changing how I produce the hitile file?

**Comment by pkerpedjiev** [comment]
Hey, this happens because the scaling is according to the currently visible tiles. Because tiles have a fixed size, they may extend beyond the edge of the view. There's a very popular open issue for changing that here: https://github.com/hms-dbmi/higlass/issues/171

I've started working on adding more advanced functionality for changing the scaling but keep getting distracted. It's definitely one of the highest priority issues though.

**Comment by aakashsur** [comment]
Gotcha, thanks!
