### ISSUE TITLE
zoomify crashes with --balance option

### ISSUE THREAD

**Issue by zhanyinx** [hms-dbmi/higlass#272]
Hi,

I was trying to create balanced (normalised, ice) maps using 

cooler zoomify --balance file.cool

This command crashed with the following error

RuntimeError: Iteration limit reached without convergence.

If I run without --balance option, it produces the file.mcool normally.
Could you help me to sort this out?

I have also another question:
1- by default, --balance is set to false right? The description is not super clear because it says that --balance/no-balance is set to false

cooler version 0.7.6

Thanks
Zhan

**Comment by hakanozadam** [comment]
Hi,

Balancing is an iterative process and it stops when the variation is below a given threshold where default is 1e-05. If it does not reach to this threshold in given number of  "max-iters", it would stop and throw the exception you saw. 

I would recommend
i) Increasing the max-iters threshold by providing arguments in the "--balance-args" option. Maximum number of iterations is 200 so you can increase it to, say 500 and try again.
ii) If your data is not deep enough and if your base bin size is small, convergence of this iterative process might be hard. So you can also try to zoomify a cooler file with a lower resolution ( in other words with a larger bin size ). 

I recommend taking a look at the documentation of cooler for balance and zoomify
`cooler balance --help`
`cooler zoomify --help`

To my knowledge, "zoomify" does not balance by default.

**Comment by nvictus** [comment]
> 1- by default, --balance is set to false right? The description is not super clear because it says that --balance/no-balance is set to false

Right, it does NOT balance by default. Good catch on the help text. That should be made clear.

>  If it does not reach to this threshold in given number of "max-iters", it would stop and throw the exception you saw.

The current version of cooler will no longer crash if convergence fails. There are now a few convergence policies, the default being to store whatever the final result may be. However, you should monitor the convergence of balancing to understand why it isn't happening fast enough. You can also inspect the unbalanced mcool in higlass.

* If the variance oscillates and explodes that suggests something is up with the data. It could be way too sparse, in which case balancing is a bad idea, or have some serious artifacts that need filtering. e.g. sometimes having many tiny contigs can cause issues. Those can be blacklisted to be excluded from balancing.
* If it is converging monotonically but slowly, you may need more stringent filtering of bad bins
* If it is only failing at high resolutions, that's likely because the data is getting too sparse. You may want to coarsen to a lower base resolution and zoomify from there, or just increase the tolerance on the variance.

You can also try to refine any zoom levels that didn't converge properly by balancing them individually after zoomify. The basic multires cool file contains integer-indexed zoom levels (use `cooler list -l <MCOOL>` to see them). You can specify any of them using `::` syntax. e.g., the following increases the stringency of the bin-level filtering and includes an explicit blacklist:

```bash
cooler balance -f -p 8 --mad-max 3 --blacklist bad_regions.bed foo.mcool::14
```
The `-f` forces overwriting of the balancing weights.

**Comment by zhanyinx** [comment]
Thanks a lot for your reply!

Zhan
