### ISSUE TITLE
empty higlass viewing area when accessed via SSL VPN

### ISSUE THREAD

**Issue by sergpolly** [hms-dbmi/higlass#325]
_Commit_: 

#### Steps to reproduce
trying to access functional HiGlass-server through Umass SSL VPN

#### Observed behavior
![screenshot from 2018-09-19 17-55-08](https://user-images.githubusercontent.com/6790270/45784220-fe44a400-bc35-11e8-9d13-34534673d13a.png)

#### Expected behavior
this private higlass server is known to be functional and works fine outside of that vpn

I think I've seen this empty-viewing area behavior beforehand ... Any ideas if that could be easily fixed ?

**Comment by pkerpedjiev** [comment]
Could you paste a screenshot of your browser's developer console?

I don't have much experience with vpns but are paths accessible relative to the address in browser location bar above?

**Comment by sergpolly** [comment]
so, here is the dev-console, lots of js errors:
![screenshot from 2018-09-19 22-21-36](https://user-images.githubusercontent.com/6790270/45792111-6d33f400-bc5a-11e8-88f9-b73a6f59f4dc.png)

here is how it looks like after adding `/api/v1/tilesets` to it ...
![screenshot from 2018-09-19 22-23-25](https://user-images.githubusercontent.com/6790270/45792189-bdab5180-bc5a-11e8-979f-7ce730fb9d00.png)

this might be relevant, and as far I understand it might imply no complicated javascript, or any at all, is allowed in some cases: https://www.networkworld.com/article/2268575/lan-wan/chapter-2--ssl-vpn-technology.html?page=6
so I feel like this might not work at all ...

for fun, here is how youtube looks like in  such vpn session:
![screenshot from 2018-09-19 22-29-21](https://user-images.githubusercontent.com/6790270/45792403-999c4000-bc5b-11e8-8322-e632d1ac7da3.png)

**Comment by pkerpedjiev** [comment]
So the issue here is the relative path. The web site that instantiates the higlass client looks for a higlass server at `/api/v1/`. But because of the relative path, the server is actually at `https://remote.umassmed.edu/,Danainfo=deepc.dekkerlab.org,SSO=U+/api/v1/`. 

The javascript seems to be working fine, as evidenced by the "Deprecated use of..." warning.

There's a few things we can do to try to get this to work but it'll take a little bit of trial and error. How important is it to you? I would love to get this to work but don't want to take up too much of your time in trying out different solutions.

Also, are you using [higlass-manage](https://github.com/hms-dbmi/higlass-manage) or using the Docker commands directly?

If you're using `higlass-manage`, you can try changing the default viewconf provider by running `higlass-manage shell` and then

    sed "s/\"\/api\/v1/\"https:\/\/remote.umassmed.edu\/,Danainfo=deepc.dekkerlab.org,SSO=U\+\/api\/v1/g" higlass-website/assets/scripts/hg-launcher.js


No matter what we do there's going to be an issue with saved viewconfs. If you export a config from the proxy url, then that url will be in the saved viewconf and somebody that isn't using the VPN may not be able to open it.

**Comment by sergpolly** [comment]
I learned about socks proxy yesterday - and managed to run the private higlass without any issues (so this is not a priority annymore) ...
I'm not sure if we need to push for this ugly web-ssl-vpn thing to work - i honestly don't know what is the purpose of that portal !? i'll try to ask umass IT, if they could explain something ...

I think we were using docker commands directly - I didn't setup the server myself.
But I'll try to play with higlass-manage - I'd need to create another higlass server for it though, as higlass.dekkerlab and deepc.dekkerlab are "production" servers - and I don't want to break those - i'll let you either way, thank you!

**Comment by sergpolly** [comment]
I've been told by our IT helpdesk that this SSL VPN web-thing is an old crappy un-maintained entity that is meant to be used only for changing passwords and downloading a proper VPN-client. 

I guess we could close this and do not waste any time on it.
